#!/usr/bin/python
import sys, urllib, re

def bloglinesCount(userEmail):
    """
    number of new bloglines entries, as the notifier would report
    them. I don't know how the security works-- it seems that just
    knowing an email address is enough.
    """

    url = "http://www.bloglines.com/notifier?user=%s" % userEmail
    txt = urllib.urlopen(url).read()
    m = re.search(r"You have (\d+) new Bloglines entries", txt)
    if m is None:
        raise ValueError("Couldn't find entry count message: %r..." % txt[:200])
    return int(m.group(1))

if __name__ == '__main__':
    # system.msg.new_bloglines_entries 
    print "%d" % (
        bloglinesCount("drewp@bigasterisk.com"))
 
