#!/usr/bin/python
import sys, mailbox
sys.path.append("/my/site/magma/munin-plugins")
import munin


def inboxCount(path="/my/mail/drewp"):
    mb = mailbox.Maildir(path, factory=None)
    count = 0
    for m in mb:
        if 'T' not in m.get_flags():
            count += 1
    return count

class Inbox(munin.Plugin):
    def fetch(self):
        return [
            ('inbox.value', inboxCount()),
            ]
    def config(self):
        return [
            ("graph_title", "maildir inbox"),
            ("graph_vlabel", "messages"),
            ("inbox.label", "inbox"),
            ]


if __name__ == '__main__':
    munin.run(Inbox)
 
