#!/usr/bin/python
import sys, mailbox

def inboxCount(path="/my/mail/drewp"):
    mb = mailbox.Maildir(path, factory=None)
    count = 0
    for m in mb:
        if 'T' not in m.get_flags():
            count += 1
    return count

if __name__ == '__main__':
    # system.msg.inbox_messages.drewp
    print inboxCount()

 
