#!/usr/bin/python
"""
./addCommand -c http://example.com/ -u "http://bigasterisk.com/foaf.rdf#drewp"

todo: check this command?
"
"""
from cmdline import prettyCommand, uriFromArg
from dbclient import nowLiteral, getCommandLog
import optparse, time

parser = optparse.OptionParser()
parser.add_option('-c', help='command uri')
parser.add_option('-u', help='user uri')
opts, args = parser.parse_args()

cl = getCommandLog()
cl.addCommand(uriFromArg(opts.c), nowLiteral(), uriFromArg(opts.u))

for c in cl.recentCommands(n=1):
    print prettyCommand(c) 
