#!/usr/bin/python
"""
web site for adding heater commands and viewing recent commands. portUpdate watches for heater
commands and turns them into parport instructions
"""
import sys, atexit
from twisted.internet import reactor
from twisted.python import log
from twisted.internet.utils import getProcessOutput 
from nevow.appserver import NevowSite
from nevow import rend, static, loaders
from rdflib.Graph import ConjunctiveGraph, ReadOnlyGraphAggregate
from rdflib import Literal, URIRef, Namespace

sys.path.append("..")
sys.path.append('/usr/lib/python2.6/dist-packages/oldxml/_xmlplus/utils')
import iso8601

from commandinference import db
from commandpage import CommandSite
from commandinference.db import XS, CMD
from commandinference.dbclient import getCommandLog

class Main(CommandSite, rend.Page):
    docFactory = loaders.xmlfile("heater.html")

    def child_static(self, ctx):
        return static.File("static")

    def render_hist(self, ctx, data):
        return getProcessOutput('/usr/bin/tail',
                                ('-n', '5', '/my/proj/room/log.parport',))

commandLog = getCommandLog()

log.startLogging(sys.stdout)

reactor.listenTCP(9016, NevowSite(Main(commandLog)))
reactor.run()
