#!/usr/bin/python
import sys, atexit, time
from twisted.internet import reactor
from twisted.python import log
from twisted.python.util import sibpath
from twisted.internet.utils import getProcessOutput 
from nevow.appserver import NevowSite
from nevow import rend, static, loaders, inevow, json, url
from rdflib.Graph import ConjunctiveGraph, ReadOnlyGraphAggregate
from rdflib import Literal, URIRef, Namespace

sys.path.append('/usr/lib/python%s/site-packages/oldxml/_xmlplus/utils' %
                sys.version[:3])
import iso8601

import db
from commandpage import CommandSite, returnPage
from dbclient import nowLiteral, getCommandLog

XS = Namespace("http://www.w3.org/2001/XMLSchema#")
CMD = Namespace("http://bigasterisk.com/magma/cmd/")

class Main(CommandSite, rend.Page):
    docFactory = loaders.xmlfile("lights.html")

    def child_static(self, ctx):
        return static.File("static")

    def child_state(self, ctx):
        """
        get state?name=bedroomred -> {'value' : 'off'}
        post state?name=bedroomred <- value=on
        """
        cmdlog = self.cmdlog
        class Ret(rend.Page):
            def renderHTTP(self, ctx):

                # should be calling child_addCommand?
                
                name = ctx.arg('name')
                assert name == 'bedroomred', name

                req = inevow.IRequest(ctx)
                if req.method == 'GET':
                    req.setHeader("Content-Type", "application/json")
                    return lastCommandValueJson(cmdlog, cls=CMD['RedLight'])
                elif req.method == 'POST':
                    cmdlog.addCommand(
                        CMD['bedroomRedLightOff'] if
                        ctx.arg('value') == 'off' else
                        CMD['bedroomRedLightOn'],
                        nowLiteral(),
                        URIRef('http://bigasterisk.com/magma/user_tbd'))
                    return url.URL.fromString("http://bigasterisk.com/magma/")
                else:
                    raise NotImplementedError
        return Ret()

def lastCommandValueJson(commandLog, cls):
    (cmd, t, u) = commandLog.lastCommandOfClass(cls)
    value = commandLog.graph.value(cmd, CMD['value'])
    print "last", (cmd, t, u, value)
    return json.serialize({u'value' : unicode(value)})


commandLog = getCommandLog()

log.startLogging(sys.stdout)

reactor.listenTCP(9018, NevowSite(Main(commandLog)))
reactor.run()
